Repository trace4cats/trace4cats-tail-sampling-extras, pull requests merged in 2021-08, with the labels that each got.

#15 Add Scala 3 build
  .github/dependabot.yml
  .github/mergify.yml
  .github/workflows/ci.yml
  .scala-steward.conf
  build.sbt
  ci-release.sbt
  modules/tail-sampling-cache-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/cache/LocalCacheSampleDecisionStore.scala
  modules/tail-sampling-caffeine/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/caffeine/CaffeineCache.scala
  modules/tail-sampling-redis-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/redis/RedisSampleDecisionStore.scala
  project/Dependencies.scala
Labels: enhancement

#17 Add new module to the root
  build.sbt
Labels: bug, skip-changelog

#18 Update cats-effect-kernel to 3.2.2
  project/Dependencies.scala
Labels: dependency-update

#20 Update cats-effect-kernel to 3.2.3
  project/Dependencies.scala
Labels: dependency-update

#21 Update scalafmt-core to 3.0.0
  .scalafmt.conf
Labels: dependency-update

#24 Update cats-effect-kernel to 3.2.4
  project/Dependencies.scala
Labels: dependency-update

#25 Update cats-effect-kernel to 3.2.5
  project/Dependencies.scala
Labels: dependency-update
